# -*- coding: utf-8 -*-
"""Copy of netflix project project .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5wD_9ZZbQC6FxZPEW5ZJxtd6le8tEJl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns



data=pd.read_csv('/content/8. Netflix Dataset (1).csv')

data.head(1)

data.tail(1)

data.shape

data.size

data.columns

data.dtypes

data.info()

data.head(1)

data[data.duplicated()]

data.drop_duplicates()

data[data.duplicated()]

data.isnull().sum()

sns.heatmap(data.isnull())

data[data['Title'].isin(['house of cards'])]

data[data['Title'].str.contains('house of cards')]

data.dtypes

data['data_N']=pd.to_datetime(data['Release_Date'])

data['data_N'].value_counts()

data['data_N'].dt.year.value_counts().plot(kind='bar')

data.head(2)

data[~data['Director'].isnull()]

"""how many movies and tv shows are n the dataset?show woth bar graph"""

data.head(2)

data.groupby('Category').Category.count()

data.head(2)

data.columns

data[(data['data_N']==2016)&(data['Category']=='Movie')]

data['year']= data['data_N'].dt.year

data.head(5)

data[(data['Category']=='Movie')&(data['year']==2020)]

"""show only the tittle of all tvshows that release in india only"""

data.head(2)

data[ (data['Category'] =='TVShow') & (data['Country']=='India')]['Title']

"""#show top 10 directors, who give the highest of tv shows& movie to netlix"""

data['Director'].value_counts().head(10)

"""##Q. 7) Show all the Records, where "Category is Movie and Type is Comedies" or "Country is United Kingdo"""

data.head(2)

data[(data['Category']=='Movie')& (data['Type']=='Comedies') | (data['Country']=='Inida')]

"""##In how many movies/shows, Tom Cruise was cast ?"""

data[data['Cast']== 'TomCruise']

data_new=data.dropna()

data.columns

"""##What are the different Ratings defined by Netflix ?"""

data['Rating'].value_counts()

"""##Q. 9.1) How many Movies got the 'TV-14' rating, in Canada ?"""

data[data['Rating']==('TV-14')]

data.head(15)

"""##Q. 9.2) How many TV Shows got the 'R' rating, after year 2018 ?"""

data[(data['Category']=="TV Show")&(data['Rating']=="R")&(data['year']>2018)]

"""##Q. 10) What is the maximum duration of a Movie/Show on Netflix ?"""

data['Duration'].unique()

data.Duration.dtypes

data[['Minutes','Unit']]= data['Duration'].str.split(' ',expand=True)

data.head()

data.Minutes.max()



"""##Q. 11) Which individual country has the Highest No. of TV Shows ?"""

data.head(2)

data_movie=data[data['Category']=='Movie']

data_movie['Country'].value_counts().head(1)



"""##. 12) How can we sort the dataset by Year ?"""

data.sort_values(by='year').head()

"""##Q. 13) Find all the instances where: Category is 'Movie' and Type is 'Dramas' or Category is 'TV Show' & Type is 'Kids' TV'."""

data[(data['Category']=='Movie')& (data['Type']=='Dramas')|(data['Category']=='TV Show')&(data['Type']=="Kids'TV")]