# -*- coding: utf-8 -*-
"""covid_case.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qrFQgZ1d2IgW4I8KEaq9mLZUHhYPnMKA
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot
import seaborn as sns

covid=pd.read_csv('/content/4. covid_19_data.csv')

covid.head()

"""
#Q. 1) Show the number of Confirmed, Deaths and Recovered cases in each Region."""

covid.count( )



covid.isnull().sum()



"""#Q. 2) Remove all the records where the Confirmed Cases is Less Than 10."""

covid[covid['Confirmed']<10]

"""#Q. 3) In which Region, maximum number of Confirmed cases were recorded ?"""

covid.groupby('Region').Confirmed.sum().sort_values(ascending= False).head()

covid.groupby('Region').Deaths.sum().sort_values(ascending= False).head()

"""##4) In which Region, minimum number of Deaths cases were recorded ?"""

covid.groupby('Region').Deaths.sum().sort_values(ascending=True).head(25)

"""##Q. 5) How many Confirmed, Deaths & Recovered cases were reported from India till 29 April 2020 ?"""

covid[covid['Region']=='India']

covid['Region'].value_counts(ascending=False)



"""##Q. 6-A ) Sort the entire data wrt No. of Confirmed cases in ascending order.

"""

covid.sort_values(by='Confirmed',ascending=True).head(15)

"""##. 6-B ) Sort the entire data wrt No. of Recovered cases in descending order."""

covid.sort_values(by='Recovered',ascending=False)























