# -*- coding: utf-8 -*-
"""police.data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuGm2DB9c72he_1FEQgczraNH3rEwNtM
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot
import seaborn as sns

police=pd.read_csv('/content/3. Police Data.csv')

police.head()

"""#Q. 1) Instruction ( For Data Cleaning ) - Remove the column that only contains missing values."""

police.isnull().sum()

police.drop(columns='country_name',inplace= True)



"""#Q. 2) Question ( Based on Filtering + Value Counts ) - For Speeding , were Men or Women stopped more often ?"""

police.head(2)

data=police[police['violation']== 'Speeding']

data['driver_gender'].value_counts()

"""##Q. 3) Question ( Groupby ) - Does gender affect who gets searched during a stop ?
Question ( mapping + data-type casting )
"""

police.head(1)

police.groupby('driver_gender')['search_conducted'].sum()

"""#Q. 4) Question ( mapping + data-type casting ) - What is the mean stop_duration ?"""

police.head(2)

police['stop_duration'].value_counts()

police['sto_duration']=police['stop_duration'].map({'0-15 Min ':7,'16-30 Min':15,'30+ Min':45})

police['sto_duration'].mean()

police.head()

"""#Q. 5) Question ( Groupby , Describe ) - Compare the age distributions for each violation."""

police.groupby('violation')['driver_age'].describe()



































